<?php

use App\Models\UserLevel;

return [
    'permissions' => [
        'view-dashboard' => [
            'name' => 'View dashboard',
            'group' => 'Pages',
            'description' => 'Access the authenticated dashboard page.',
        ],
        'manage-profile' => [
            'name' => 'Manage profile',
            'group' => 'Account',
            'description' => 'Open and update the signed-in user profile.',
        ],
        'view-users' => [
            'name' => 'See all users',
            'group' => 'Users',
            'description' => 'Open the users list page.',
        ],
        'create-users' => [
            'name' => 'Add new users',
            'group' => 'Users',
            'description' => 'Open the add user page and create users.',
        ],
        'update-users' => [
            'name' => 'Update users',
            'group' => 'Users',
            'description' => 'Open edit user pages and save user updates.',
        ],
        'view-company' => [
            'name' => 'View company',
            'group' => 'Company',
            'description' => 'Open the company profile page.',
        ],
        'manage-access' => [
            'name' => 'Manage access control',
            'group' => 'Access Control',
            'description' => 'Grant or deny user level permissions.',
        ],
        'manage-notifications' => [
            'name' => 'Manage notifications',
            'group' => 'Notifications',
            'description' => 'Open, update, and delete dashboard notifications.',
        ],
        'view-projects' => [
            'name' => 'See all projects',
            'group' => 'Projects',
            'description' => 'Open the projects list and project detail pages.',
        ],
        'create-projects' => [
            'name' => 'Add new projects',
            'group' => 'Projects',
            'description' => 'Open the add project page and create projects.',
        ],
        'update-projects' => [
            'name' => 'Update projects',
            'group' => 'Projects',
            'description' => 'Open edit project pages and save project updates.',
        ],
        'delete-projects' => [
            'name' => 'Delete projects',
            'group' => 'Projects',
            'description' => 'Remove project records.',
        ],
        'view-bids' => [
            'name' => 'See all bids',
            'group' => 'Bids',
            'description' => 'Open the bids list and bid detail pages.',
        ],
        'create-bids' => [
            'name' => 'Add new bids',
            'group' => 'Bids',
            'description' => 'Open the add bid page and create bids.',
        ],
        'update-bids' => [
            'name' => 'Update bids',
            'group' => 'Bids',
            'description' => 'Open edit bid pages and save bid updates.',
        ],
        'delete-bids' => [
            'name' => 'Delete bids',
            'group' => 'Bids',
            'description' => 'Remove bid records.',
        ],
        'view-quotations' => [
            'name' => 'See all quotations',
            'group' => 'Quotations',
            'description' => 'Open the quotations list and quotation detail pages.',
        ],
        'create-quotations' => [
            'name' => 'Add new quotations',
            'group' => 'Quotations',
            'description' => 'Open the add quotation page and create quotations.',
        ],
        'update-quotations' => [
            'name' => 'Update quotations',
            'group' => 'Quotations',
            'description' => 'Open edit quotation pages and save quotation updates.',
        ],
        'delete-quotations' => [
            'name' => 'Delete quotations',
            'group' => 'Quotations',
            'description' => 'Remove quotation records.',
        ],
        'view-products' => [
            'name' => 'See all products',
            'group' => 'Products',
            'description' => 'Open the products list and product detail pages.',
        ],
        'create-products' => [
            'name' => 'Add new products',
            'group' => 'Products',
            'description' => 'Open the add product page and create doors or parts.',
        ],
        'update-products' => [
            'name' => 'Update products',
            'group' => 'Products',
            'description' => 'Open edit product pages and save product updates.',
        ],
        'delete-products' => [
            'name' => 'Delete products',
            'group' => 'Products',
            'description' => 'Remove product records.',
        ],
        'view-services' => [
            'name' => 'See all services',
            'group' => 'Services',
            'description' => 'Open the services list and service detail pages.',
        ],
        'create-services' => [
            'name' => 'Add new services',
            'group' => 'Services',
            'description' => 'Open the add service page and create services.',
        ],
        'update-services' => [
            'name' => 'Update services',
            'group' => 'Services',
            'description' => 'Open edit service pages and save service updates.',
        ],
        'delete-services' => [
            'name' => 'Delete services',
            'group' => 'Services',
            'description' => 'Remove service records.',
        ],
        'view-contractors' => [
            'name' => 'See all contractors',
            'group' => 'Contractors',
            'description' => 'Open the general contractors list page.',
        ],
        'create-contractors' => [
            'name' => 'Add new contractors',
            'group' => 'Contractors',
            'description' => 'Open the add contractor page and create general contractors.',
        ],
        'update-contractors' => [
            'name' => 'Update contractors',
            'group' => 'Contractors',
            'description' => 'Open edit contractor pages and save contractor updates.',
        ],
        'delete-contractors' => [
            'name' => 'Delete contractors',
            'group' => 'Contractors',
            'description' => 'Remove contractor records.',
        ],
        'view-employees' => [
            'name' => 'See all employees',
            'group' => 'Employees',
            'description' => 'Open the employees list page.',
        ],
        'create-employees' => [
            'name' => 'Add new employees',
            'group' => 'Employees',
            'description' => 'Open the add employee page and create employees.',
        ],
        'update-employees' => [
            'name' => 'Update employees',
            'group' => 'Employees',
            'description' => 'Open edit employee pages and save employee updates.',
        ],
        'delete-employees' => [
            'name' => 'Delete employees',
            'group' => 'Employees',
            'description' => 'Remove employee records.',
        ],
    ],

    'defaults' => [
        UserLevel::SUPER_ADMIN => [
            'view-dashboard',
            'manage-profile',
            'view-users',
            'create-users',
            'update-users',
            'view-company',
            'manage-access',
            'manage-notifications',
            'view-projects',
            'create-projects',
            'update-projects',
            'delete-projects',
            'view-bids',
            'create-bids',
            'update-bids',
            'delete-bids',
            'view-quotations',
            'create-quotations',
            'update-quotations',
            'delete-quotations',
            'view-products',
            'create-products',
            'update-products',
            'delete-products',
            'view-services',
            'create-services',
            'update-services',
            'delete-services',
            'view-contractors',
            'create-contractors',
            'update-contractors',
            'delete-contractors',
            'view-employees',
            'create-employees',
            'update-employees',
            'delete-employees',
        ],
        UserLevel::ADMINISTRATOR => [
            'view-dashboard',
            'manage-profile',
            'view-company',
            'view-projects',
            'create-projects',
            'update-projects',
            'delete-projects',
            'view-bids',
            'create-bids',
            'update-bids',
            'delete-bids',
            'view-quotations',
            'create-quotations',
            'update-quotations',
            'delete-quotations',
            'view-products',
            'create-products',
            'update-products',
            'delete-products',
            'view-services',
            'create-services',
            'update-services',
            'delete-services',
            'view-contractors',
            'create-contractors',
            'update-contractors',
            'delete-contractors',
            'view-employees',
            'create-employees',
            'update-employees',
            'delete-employees',
        ],
        UserLevel::ADMIN => [
            'view-dashboard',
            'manage-profile',
            'view-company',
            'view-projects',
            'create-projects',
            'update-projects',
            'view-bids',
            'create-bids',
            'update-bids',
            'view-quotations',
            'create-quotations',
            'update-quotations',
            'view-products',
            'create-products',
            'update-products',
            'view-services',
            'create-services',
            'update-services',
            'view-contractors',
            'create-contractors',
            'update-contractors',
        ],
        UserLevel::PROJECT_MANAGER => [
            'view-dashboard',
            'manage-profile',
            'view-projects',
            'update-projects',
            'view-bids',
            'update-bids',
            'view-quotations',
            'update-quotations',
            'view-products',
            'update-products',
            'view-services',
            'update-services',
            'view-contractors',
            'create-contractors',
            'update-contractors',
        ],
        UserLevel::USER => [
            'view-dashboard',
            'manage-profile',
        ],
        UserLevel::VISITOR => [
            'manage-profile',
        ],
    ],
];
