<?php

namespace App\Support;

use App\Models\BidTextField;
use Illuminate\Support\Carbon;

class DocumentLayoutElements
{
    public const TYPES = ['text', 'image', 'divider', 'spacer', 'date', 'validity', 'company', 'table'];

    public const ZONES = ['header', 'intro', 'body', 'footer'];

    /** Sections currently enabled in the designer; others are kept off until they are built. */
    public const FONT_FAMILIES = [
        'default' => '',
        'helvetica' => 'Helvetica, Arial, sans-serif',
        'arial' => 'Arial, Helvetica, sans-serif',
        'verdana' => 'Verdana, Geneva, sans-serif',
        'tahoma' => 'Tahoma, Geneva, sans-serif',
        'trebuchet' => '"Trebuchet MS", Helvetica, sans-serif',
        'georgia' => 'Georgia, serif',
        'times' => '"Times New Roman", Times, serif',
        'courier' => '"Courier New", Courier, monospace',
        'geist' => '"Geist Variable", Arial, sans-serif',
        'calibri' => 'Calibri, Candara, Arial, sans-serif',
        'aptos' => 'Aptos, Calibri, Arial, sans-serif',
        'segoe' => '"Segoe UI", Tahoma, Arial, sans-serif',
        'century_gothic' => '"Century Gothic", "Apple Gothic", Arial, sans-serif',
        'lucida_sans' => '"Lucida Sans Unicode", "Lucida Grande", sans-serif',
        'arial_narrow' => '"Arial Narrow", Arial, sans-serif',
        'cambria' => 'Cambria, Georgia, serif',
        'palatino' => '"Palatino Linotype", Palatino, "Book Antiqua", serif',
        'garamond' => 'Garamond, "Baskerville Old Face", "Times New Roman", serif',
        'baskerville' => 'Baskerville, "Baskerville Old Face", Georgia, serif',
        'bookman' => '"Bookman Old Style", "URW Bookman", Georgia, serif',
        'consolas' => 'Consolas, "Courier New", monospace',
        'menlo' => 'Menlo, Monaco, Consolas, monospace',
        'lucida_console' => '"Lucida Console", Monaco, monospace',
        'impact' => 'Impact, "Arial Black", sans-serif',
        'arial_black' => '"Arial Black", Arial, sans-serif',
        'comic_sans' => '"Comic Sans MS", "Comic Sans", cursive',
    ];

    public const DEFAULT_HEADER_HEIGHT = 160;

    public const ACTIVE_ZONES = ['header'];

    public const ALIGNMENTS = ['left', 'center', 'right', 'justify'];

    public const MAX_ELEMENTS = 1000;

    public const COMPANY_FIELDS = [
        'company_name' => 'Company name',
        'company_speciality' => 'Company speciality',
        'company_legal_name' => 'Legal name',
        'company_address' => 'Address',
        'company_phone' => 'Phone',
        'company_contact_phone' => 'Contact phone',
        'company_email' => 'Email',
        'company_website' => 'Website',
        'company_contact_url' => 'Contact page',
    ];

    public const DEFAULT_COMPANY_FIELDS = ['company_name', 'company_address', 'company_phone', 'company_email'];

    public const FIELDS = [
        'company_name' => ['label' => 'Company name', 'group' => 'Company', 'sample' => 'Gateway Door Systems'],
        'company_speciality' => ['label' => 'Company speciality', 'group' => 'Company', 'sample' => 'Commercial door systems'],
        'company_address' => ['label' => 'Company address', 'group' => 'Company', 'sample' => '245 Market Street · Portland, OR 97201'],
        'company_phone' => ['label' => 'Company phone', 'group' => 'Company', 'sample' => '(503) 555-0142'],
        'company_email' => ['label' => 'Company email', 'group' => 'Company', 'sample' => 'info@example.com'],
        'company_legal_name' => ['label' => 'Company legal name', 'group' => 'Company', 'sample' => 'Gateway Door Systems LLC'],
        'company_contact_phone' => ['label' => 'Company contact phone', 'group' => 'Company', 'sample' => '(503) 555-0199'],
        'company_website' => ['label' => 'Company website', 'group' => 'Company', 'sample' => 'www.example.com'],
        'company_contact_url' => ['label' => 'Company contact page', 'group' => 'Company', 'sample' => 'www.example.com/contact'],
        'document_title' => ['label' => 'Document title', 'group' => 'Document', 'sample' => 'Northwest Commons'],
        'document_number' => ['label' => 'Document number', 'group' => 'Document', 'sample' => 'BID-2025-014'],
        'generated_date' => ['label' => 'Date generated', 'group' => 'Document', 'sample' => 'October 7, 2025'],
        'generated_by' => ['label' => 'Generated by', 'group' => 'Document', 'sample' => 'Alex Morgan'],
        'year' => ['label' => 'Year', 'group' => 'Document', 'sample' => '2025'],
        'project_name' => ['label' => 'Project name', 'group' => 'Project', 'sample' => 'Northwest Commons'],
        'project_number' => ['label' => 'Project number', 'group' => 'Project', 'sample' => 'P-2025-014'],
        'project_address' => ['label' => 'Project address', 'group' => 'Project', 'sample' => '245 Market Street, Portland, OR'],
        'contractor_name' => ['label' => 'Contractor company', 'group' => 'Contractor', 'sample' => 'Harbor Facilities'],
        'contractor_contact_name' => ['label' => 'Contractor contact', 'group' => 'Contractor', 'sample' => 'Alex Morgan'],
        'contractor_email' => ['label' => 'Contractor email', 'group' => 'Contractor', 'sample' => 'contact@example.com'],
        'contractor_phone' => ['label' => 'Contractor phone', 'group' => 'Contractor', 'sample' => '(503) 555-0100'],
        'contractor_address' => ['label' => 'Contractor address', 'group' => 'Contractor', 'sample' => '125 Harbor Street, Portland, OR'],
        'contractor_website' => ['label' => 'Contractor website', 'group' => 'Contractor', 'sample' => 'www.example.com'],
        'bid_number' => ['label' => 'Bid number', 'group' => 'Bid', 'sample' => 'P-2025-014'],
        'bid_date' => ['label' => 'Bid date', 'group' => 'Bid', 'sample' => 'October 7, 2025'],
        'bid_stage' => ['label' => 'Bid stage', 'group' => 'Bid', 'sample' => 'Proposal'],
        'validity_30' => ['label' => 'Validity date (30 days)', 'group' => 'Document', 'sample' => 'November 6, 2025'],
        'validity_60' => ['label' => 'Validity date (60 days)', 'group' => 'Document', 'sample' => 'December 6, 2025'],
        'validity_90' => ['label' => 'Validity date (90 days)', 'group' => 'Document', 'sample' => 'January 5, 2026'],
    ];

    /**
     * Field catalog for the editor, using real company values when available.
     *
     * @return list<array<string, string>>
     */
    public static function fieldCatalog(): array
    {
        $company = self::companyValues();
        $catalog = [];

        $fields = self::FIELDS;
        foreach (BidApplicationText::PLACEHOLDERS as $key => $label) {
            if (isset($fields[$key])) {
                continue;
            }
            $group = match (true) {
                in_array($key, BidApplicationText::QUOTATION_FIELDS, true) => 'Quotation',
                str_starts_with($key, 'company_') => 'Company',
                str_starts_with($key, 'contractor_'), str_starts_with($key, 'customer_') => 'Contractor',
                in_array($key, ['project_name', 'project_number', 'project_address', 'site_address', 'scope_of_work', 'estimated_start_date', 'estimated_end_date'], true) => 'Project',
                in_array($key, ['today', 'authorized_representative'], true) => 'Bid',
                default => 'Totals on this bid',
            };
            $alias = match ($key) {
                'customer_name' => 'contractor_contact_name',
                'customer_company' => 'contractor_name',
                'site_address' => 'project_address',
                'today' => 'generated_date',
                default => null,
            };
            $fields[$key] = [
                'label' => $label, 'group' => $group,
                'sample' => $alias ? self::FIELDS[$alias]['sample'] : '{{'.$key.'}}',
            ];
        }
        $samples = [];
        foreach ($fields as $key => $meta) {
            $samples[$key] = ($company[$key] ?? '') !== '' ? $company[$key] : $meta['sample'];
            $catalog[] = [
                'key' => $key,
                'label' => $meta['label'],
                'group' => $meta['group'],
                'sample' => $samples[$key],
            ];
        }

        foreach (BidTextField::query()->orderBy('name')->get(['key', 'name', 'source', 'value']) as $field) {
            if (isset($fields[$field->key])) {
                continue;
            }
            $catalog[] = [
                'key' => $field->key, 'label' => $field->name, 'group' => 'Your fields',
                'source' => (string) $field->source,
                'sourceLabel' => BidApplicationText::PLACEHOLDERS[$field->source] ?? '',
                'sample' => $samples[$field->source] ?? ($field->value ?: '{{'.$field->key.'}}'),
            ];
        }

        return $catalog;
    }

    /**
     * @return array<string, string>
     */
    public static function companyValues(): array
    {
        $company = DocumentLogo::company();

        if (! $company) {
            return [];
        }

        $address = implode(' · ', array_filter([
            $company->address_line_1,
            $company->address_line_2,
            implode(', ', array_filter([$company->city, $company->state, $company->postal_code])),
            $company->country,
        ]));

        return [
            'company_name' => (string) $company->name,
            'company_speciality' => (string) $company->speciality,
            'company_address' => $address,
            'company_phone' => (string) ($company->contact_phone_number ?: $company->phone_number),
            'company_email' => (string) $company->email,
            'company_legal_name' => (string) $company->legal_name,
            'company_contact_phone' => (string) $company->contact_phone_number,
            'company_website' => (string) $company->website_url,
            'company_contact_url' => (string) $company->contact_url,
        ];
    }

    /**
     * @param  array<string, mixed>  $data
     * @return array<string, string>
     */
    public static function fieldValues(array $data): array
    {
        $company = self::companyValues();
        $pick = fn (string $key, string $fallback = ''): string => (string) ($data[$key] ?? $fallback);

        $validityBase = Carbon::parse($data['bidDate'] ?? $data['quotedAt'] ?? now());

        return [
            ...array_combine(BidApplicationText::QUOTATION_FIELDS,
                array_map(fn (string $key): string => $pick($key), BidApplicationText::QUOTATION_FIELDS)),
            'contractor_name' => $pick('contractor_name'),
            'contractor_contact_name' => $pick('contractor_contact_name'),
            'contractor_email' => $pick('contractor_email'),
            'contractor_phone' => $pick('contractor_phone'),
            'contractor_address' => $pick('contractor_address'),
            'contractor_website' => $pick('contractor_website'),
            'company_name' => $company['company_name'] ?? $pick('companyName'),
            'company_speciality' => $company['company_speciality'] ?? $pick('companySpeciality'),
            'company_address' => $company['company_address'] ?? $pick('companyAddress'),
            'company_phone' => $company['company_phone'] ?? $pick('companyPhone'),
            'company_email' => $company['company_email'] ?? $pick('companyEmail'),
            'company_legal_name' => $company['company_legal_name'] ?? '',
            'company_contact_phone' => $company['company_contact_phone'] ?? '',
            'company_website' => $company['company_website'] ?? '',
            'company_contact_url' => $company['company_contact_url'] ?? '',
            'document_title' => $pick('title'),
            'document_number' => $pick('bidNumber', $pick('quotationNumber', $pick('projectNumber'))),
            'generated_date' => now()->format('F j, Y'),
            'generated_by' => $pick('generatedBy'),
            'year' => (string) now()->year,
            'project_name' => $pick('projectName'),
            'project_number' => $pick('projectNumber'),
            'project_address' => $pick('projectAddress'),
            'bid_number' => $pick('bidNumber'),
            'bid_date' => $pick('bidDate'),
            'bid_stage' => $pick('stageLabel'),
            'validity_30' => $validityBase->copy()->addDays(30)->format('F j, Y'),
            'validity_60' => $validityBase->copy()->addDays(60)->format('F j, Y'),
            'validity_90' => $validityBase->copy()->addDays(90)->format('F j, Y'),
        ];
    }

    /**
     * @param  array<string, string>  $values
     */
    public static function replaceFields(string $text, array $values): string
    {
        return preg_replace_callback(
            '/\{\{\s*([a-z_]+)\s*\}\}/',
            fn (array $match): string => $values[$match[1]] ?? '',
            $text,
        ) ?? $text;
    }

    /**
     * @return list<array{label: string, value: string}>
     */
    public static function tableItems(mixed $items): array
    {
        if (! is_array($items)) {
            return [];
        }

        $clean = [];

        foreach (array_slice(array_values($items), 0, 40) as $item) {
            if (is_array($item)) {
                $clean[] = [
                    'label' => mb_substr((string) ($item['label'] ?? ''), 0, 300),
                    'value' => mb_substr((string) ($item['value'] ?? ''), 0, 300),
                ];
            }
        }

        return $clean;
    }

    private static function indexedStyles(mixed $styles, int $limit): array
    {
        if (! is_array($styles)) {
            return [];
        }

        $styles = array_intersect_key($styles, array_fill_keys(range(0, $limit - 1), true));
        if ($styles === []) {
            return [];
        }
        $rows = [];
        for ($index = 0; $index <= max(array_keys($styles)); $index++) {
            $rows[] = $styles[$index] ?? null;
        }

        return $rows;
    }

    private static function rowStyles(mixed $styles, int $limit = 60, bool $pdf = false): array
    {
        return array_map(function ($style) use ($pdf): ?array {
            if (! is_array($style)) {
                return null;
            }
            $clean = [];
            foreach (['bold', 'italic', 'underline'] as $key) {
                if (isset($style[$key]) && in_array($style[$key], [true, false, 0, 1, '0', '1'], true)) {
                    $clean[$key] = (bool) $style[$key];
                }
            }
            if (isset($style['font_family']) && is_string($style['font_family']) && array_key_exists($style['font_family'], self::FONT_FAMILIES)) {
                $clean['font_family'] = $style['font_family'];
            }
            if (isset($style['font_size']) && is_numeric($style['font_size'])) {
                $clean['font_size'] = $pdf ? max(1, min(200, (float) $style['font_size'])) : max(8, min(48, (int) $style['font_size']));
            }
            if (isset($style['color']) && is_string($style['color']) && preg_match('/^#[A-Fa-f0-9]{6}$/', $style['color'])) {
                $clean['color'] = strtolower($style['color']);
            }
            if (isset($style['line_height']) && is_numeric($style['line_height'])) {
                $clean['line_height'] = self::lineHeight($style['line_height']);
            }
            if (in_array($style['align'] ?? null, self::ALIGNMENTS, true)) {
                $clean['align'] = $style['align'];
            }
            if (in_array($style['text_case'] ?? null, ['original', 'camel', 'uppercase', 'lowercase'], true)) {
                $clean['text_case'] = $style['text_case'];
            }

            return $clean ?: null;
        }, self::indexedStyles($styles, $limit));
    }

    private static function cellStyles(mixed $styles, bool $pdf = false): array
    {
        return array_map(
            fn ($row): ?array => is_array($row) ? self::rowStyles($row, 12, $pdf) : null,
            self::indexedStyles($styles, 60),
        );
    }

    /**
     * @return list<string>
     */
    public static function companyFields(mixed $fields): array
    {
        if (! is_array($fields)) {
            return self::DEFAULT_COMPANY_FIELDS;
        }

        return array_values(array_unique(array_filter(
            $fields,
            fn (mixed $key): bool => is_string($key) && isset(self::COMPANY_FIELDS[$key]),
        )));
    }

    /**
     * @return array{body: string, footer: string, header_height: float}
     */
    public static function zoneColors(mixed $colors): array
    {
        $colors = is_array($colors) ? $colors : [];
        $clean = fn (mixed $value): string => is_string($value) && preg_match('/^#[A-Fa-f0-9]{6}$/', $value) === 1 ? strtolower($value) : '';

        $height = is_numeric($colors['header_height'] ?? null) ? (float) $colors['header_height'] : 0;
        $height = $height > 0 ? round(max(60, min(4000, $height)), 2) : self::DEFAULT_HEADER_HEIGHT;
        if (is_float($height) && fmod($height, 1.0) === 0.0) {
            $height = (int) $height;
        }

        return [
            'body' => $clean($colors['body'] ?? null),
            'footer' => $clean($colors['footer'] ?? null),
            'header_height' => $height,
        ];
    }

    private static function lineHeight(mixed $value): float
    {
        $height = is_numeric($value) ? (float) $value : 1.35;

        return round(max(0.5, min(4, $height)), 2);
    }

    /**
     * @param  array<string, mixed>  $element
     */
    private static function estimateHeight(array $element): int
    {
        $size = max(8, min(48, (int) ($element['font_size'] ?? 12)));

        return match ($element['type'] ?? 'text') {
            'image' => 80,
            'divider' => max(1, (int) ($element['height'] ?? 2)) + 12,
            'spacer' => max(1, (int) ($element['height'] ?? 16)),
            'table' => isset($element['cells'])
                ? max(1, count($element['cells'])) * 32
                : max(1, count((array) ($element['items'] ?? []))) * 28,
            'company' => max(1, count((array) ($element['fields'] ?? []))) * (int) ($size * 1.5),
            default => (int) ($size * 1.5) + 6,
        };
    }

    /**
     * Normalizes stored or submitted elements into a safe, fully-populated shape.
     *
     * @return list<array<string, mixed>>
     */
    public static function sanitize(mixed $elements): array
    {
        if (! is_array($elements)) {
            return [];
        }

        $clean = [];
        $cursor = 8;

        foreach (array_slice(array_values($elements), 0, self::MAX_ELEMENTS) as $index => $element) {
            if (! is_array($element) || ! in_array($element['type'] ?? null, self::TYPES, true)) {
                continue;
            }

            $id = preg_replace('/[^A-Za-z0-9_-]/', '', (string) ($element['id'] ?? ''));
            $src = (string) ($element['src'] ?? '');

            $pdfPage = is_string($element['pdf_page'] ?? null) && preg_match('/^[A-Za-z0-9_-]{1,40}$/', $element['pdf_page']) === 1;
            $width = $pdfPage ? max(0.1, min(100, (float) ($element['width'] ?? 100))) : max(5, min(100, (int) ($element['width'] ?? 100)));
            $align = in_array($element['align'] ?? null, self::ALIGNMENTS, true) ? $element['align'] : 'left';
            $hasPosition = isset($element['x'], $element['y']) && is_numeric($element['x']) && is_numeric($element['y']);
            $x = $hasPosition
                ? (float) $element['x']
                : match ($align) {
                    'center' => (100 - $width) / 2,
                    'right' => 100 - $width,
                    default => 0.0,
                };
            $y = $hasPosition ? (float) $element['y'] : $cursor;
            $cursor = $y + self::estimateHeight($element) + 6;

            $clean[] = [
                'id' => $id !== '' ? substr($id, 0, 40) : 'el-'.$index,
                'x' => round(max(0, min(100 - $width, $x)), $pdfPage ? 6 : 1),
                'y' => $pdfPage ? round(max(0, min(4000, $y)), 4) : (int) max(0, min(2000, $y)),
                'type' => $element['type'],
                'zone' => in_array($element['zone'] ?? null, ['intro', 'body', 'footer'], true) ? $element['zone'] : 'header',
                'content' => mb_substr((string) ($element['content'] ?? ''), 0, 20000),
                'src' => EditorImage::isStoredSrc($src) ? $src : '',
                'align' => $align,
                'width' => $width,
                'height' => $pdfPage ? max(1, min(4000, (float) ($element['height'] ?? 16))) : max(1, min(400, (int) ($element['height'] ?? 16))),
                'font_size' => $pdfPage ? max(1, min(200, (float) ($element['font_size'] ?? 12))) : max(8, min(48, (int) ($element['font_size'] ?? 12))),
                ...($pdfPage ? [
                    'pdf_page' => $element['pdf_page'],
                    'pdf_page_height' => max(60, min(4000, (float) ($element['pdf_page_height'] ?? 160))),
                    'pdf_background' => $element['type'] === 'image' && ! empty($element['pdf_background']),
                    'pdf_font_src' => ImportedPdfFont::family($element['pdf_font_src'] ?? null) ? $element['pdf_font_src'] : null,
                    'pdf_font_name' => mb_substr((string) ($element['pdf_font_name'] ?? ''), 0, 120),
                    ...(isset($element['pdf_text_runs']) && is_array($element['pdf_text_runs']) ? [
                        'pdf_text_runs' => array_map(static fn (array $run): array => [
                            'line' => max(0, min(199, (int) ($run['line'] ?? 0))),
                            'offset' => max(0, min(10000, (int) ($run['offset'] ?? 0))),
                            'length' => max(1, min(10000, (int) ($run['length'] ?? 1))),
                            'x' => max(0, min(700, (float) ($run['x'] ?? 0))),
                            'y' => max(0, min(4000, (float) ($run['y'] ?? 0))),
                            'width' => max(0.1, min(700, (float) ($run['width'] ?? 1))),
                            'height' => max(1, min(200, (float) ($run['height'] ?? 12))),
                            'font_size' => max(1, min(200, (float) ($run['font_size'] ?? 12))),
                            'font_family' => array_key_exists($run['font_family'] ?? '', self::FONT_FAMILIES) ? $run['font_family'] : 'default',
                            'pdf_font_src' => ImportedPdfFont::family($run['pdf_font_src'] ?? null) ? $run['pdf_font_src'] : null,
                            'pdf_font_name' => mb_substr((string) ($run['pdf_font_name'] ?? ''), 0, 120),
                            'bold' => (bool) ($run['bold'] ?? false),
                            'italic' => (bool) ($run['italic'] ?? false),
                            'color' => DocumentAppearance::normalize($run['color'] ?? '#000000'),
                        ], array_values(array_filter(array_slice($element['pdf_text_runs'], 0, 1000), 'is_array'))),
                    ] : []),
                    ...(isset($element['pdf_line_count']) ? [
                        'pdf_line_count' => max(1, min(200, (int) $element['pdf_line_count'])),
                    ] : []),
                    ...(isset($element['pdf_line_spacing']) ? [
                        'pdf_line_spacing' => max(0.5, min(400, (float) $element['pdf_line_spacing'])),
                    ] : []),
                    ...(isset($element['pdf_list_lines']) && is_array($element['pdf_list_lines']) ? [
                        'pdf_list_lines' => array_map(fn ($count): int => max(1, min(200, (int) $count)), array_slice(array_values($element['pdf_list_lines']), 0, 200)),
                    ] : []),
                    ...(in_array($element['pdf_bullet_style'] ?? null, ['disc', 'circle', 'square'], true) ? [
                        'pdf_bullet_style' => $element['pdf_bullet_style'],
                    ] : []),
                ] : []),
                'font_family' => array_key_exists($element['font_family'] ?? null, self::FONT_FAMILIES) ? $element['font_family'] : 'default',
                'text_case' => DocumentTextCase::normalize((string) ($element['text_case'] ?? 'original')),
                'fields' => self::companyFields($element['fields'] ?? null),
                'items' => self::tableItems($element['items'] ?? null),
                'header_row' => (bool) ($element['header_row'] ?? false),
                'header_color' => DocumentAppearance::normalize($element['header_color'] ?? '#ffffff'),
                'stripe_direction' => in_array($element['stripe_direction'] ?? null, ['rows', 'columns'], true) ? $element['stripe_direction'] : 'none',
                'table_background' => DocumentAppearance::normalize((string) ($element['table_background'] ?? ''), ''),
                'column_colors' => array_map(
                    fn ($color) => $color === null ? null : DocumentAppearance::normalize((string) $color, ''),
                    array_slice(is_array($element['column_colors'] ?? null) ? array_values($element['column_colors']) : [], 0, 12),
                ),
                'row_styles' => self::rowStyles($element['row_styles'] ?? null, 60, $pdfPage),
                'cell_styles' => self::cellStyles($element['cell_styles'] ?? null, $pdfPage),
                'stripe_color_a' => DocumentAppearance::normalize((string) ($element['stripe_color_a'] ?? ''), '#ffffff'),
                'stripe_color_b' => DocumentAppearance::normalize((string) ($element['stripe_color_b'] ?? ''), '#f3f4f6'),
                'cells' => isset($element['cells']) && is_array($element['cells'])
                    ? array_map(fn ($row) => array_map(fn ($cell) => mb_substr((string) $cell, 0, 2000), array_slice(is_array($row) ? array_values($row) : [], 0, 12)), array_slice(array_values($element['cells']), 0, 60))
                    : null,
                'label_bg' => DocumentAppearance::normalize((string) ($element['label_bg'] ?? ''), ''),
                'border_color' => DocumentAppearance::normalize((string) ($element['border_color'] ?? ''), '#cbd5e1'),
                'label_width' => max(10, min(70, (int) ($element['label_width'] ?? 30))),
                'column_widths' => array_values(array_filter(array_slice((array) ($element['column_widths'] ?? []), 0, 12),
                    fn ($value): bool => is_numeric($value) && $value > 0 && $value <= 100)),
                'row_heights' => array_values(array_filter(array_slice((array) ($element['row_heights'] ?? []), 0, 60),
                    fn ($value): bool => is_numeric($value) && $value >= 1 && $value <= 4000)),
                'cell_backgrounds' => array_map(fn ($row) => array_map(
                    fn ($color) => DocumentAppearance::normalize((string) $color, '#ffffff'),
                    array_slice(is_array($row) ? array_values($row) : [], 0, 12)),
                    array_slice((array) ($element['cell_backgrounds'] ?? []), 0, 60)),
                'cell_borders' => array_map(fn ($row) => array_map(function ($borders) {
                    $clean = [];
                    foreach (['top', 'right', 'bottom', 'left'] as $side) {
                        $value = is_array($borders) ? ($borders[$side] ?? 'none') : 'none';
                        $clean[$side] = is_string($value) && preg_match('/^(none|(?:\\d+(?:\\.\\d+)?)px solid #[A-Fa-f0-9]{6})$/', $value) ? $value : 'none';
                    }
                    return $clean;
                }, array_slice(is_array($row) ? array_values($row) : [], 0, 12)), array_slice((array) ($element['cell_borders'] ?? []), 0, 60)),
                'cell_spans' => array_map(fn ($row) => array_map(fn ($span) => [
                    'rows' => max(0, min(60, (int) ($span['rows'] ?? 1))),
                    'columns' => max(0, min(12, (int) ($span['columns'] ?? 1))),
                ], array_slice(is_array($row) ? array_values($row) : [], 0, 12)), array_slice((array) ($element['cell_spans'] ?? []), 0, 60)),
                'layout' => ($element['layout'] ?? null) === 'table' ? 'table' : 'lines',
                'border' => (bool) ($element['border'] ?? true),
                'show_labels' => (bool) ($element['show_labels'] ?? false),
                'columns' => max(1, min(12, (int) ($element['columns'] ?? 2))),
                'inline' => (bool) ($element['inline'] ?? false),
                'bold' => (bool) ($element['bold'] ?? false),
                'italic' => (bool) ($element['italic'] ?? false),
                'underline' => (bool) ($element['underline'] ?? false),
                'line_height' => self::lineHeight($element['line_height'] ?? 1.35),
                'list_style' => in_array($element['list_style'] ?? null, ['bullet', 'numbered'], true) ? $element['list_style'] : 'none',
                'validity_days' => in_array((int) ($element['validity_days'] ?? 30), [30, 60, 90], true) ? (int) ($element['validity_days'] ?? 30) : 30,
                'color' => DocumentAppearance::normalize((string) ($element['color'] ?? ''), '#111827'),
            ];
        }

        return $clean;
    }

    /**
     * @param  list<array<string, mixed>>  $elements
     */
    public static function resolveTableFields(string $text, array $elements): string
    {
        return preg_replace_callback(
            '/\{\{\s*table_cell:([A-Za-z0-9_-]+):(\d+):(\d+)\s*\}\}/',
            function (array $match) use ($elements): string {
                $row = (int) $match[2];
                $column = (int) $match[3];
                if ($row < 1 || $column < 1) {
                    return '[Missing table cell]';
                }
                foreach ($elements as $table) {
                    if (($table['id'] ?? null) !== $match[1] || ($table['type'] ?? null) !== 'table') {
                        continue;
                    }
                    if (is_array($table['cells'] ?? null)) {
                        return $table['cells'][$row - 1][$column - 1] ?? '[Missing table cell]';
                    }
                    $pairs = min(3, max(1, (int) ($table['columns'] ?? 2)));
                    if ($column > $pairs * 2) {
                        return '[Missing table cell]';
                    }
                    $item = $table['items'][($row - 1) * $pairs + intdiv($column - 1, 2)] ?? null;

                    return $item[$column % 2 === 1 ? 'label' : 'value'] ?? '[Missing table cell]';
                }

                return '[Missing table cell]';
            },
            $text,
        ) ?? $text;
    }

    public static function render(array $elements, string $zone, string $bannerColor = '#065f46', array $values = [], string $background = '', int $headerHeight = self::DEFAULT_HEADER_HEIGHT): string
    {
        $sources = $elements;
        $elements = array_map(function (array $element) use ($sources): array {
            if ($element['type'] === 'text') {
                $element['content'] = self::resolveTableFields($element['content'], $sources);
            }

            return $element;
        }, $elements);
        $items = array_filter(
            $elements,
            fn (array $element): bool => ($element['zone'] ?? 'header') === $zone,
        );

        if ($items === []) {
            return '';
        }

        if ($zone === 'header') {
            return self::renderFreeHeader($items, $bannerColor, $values, $headerHeight);
        }

        $html = '';

        $banner = $zone === 'header' || $background !== '';
        $rows = [];

        foreach ($items as $element) {
            if (! empty($element['inline']) && $rows !== []) {
                $rows[array_key_last($rows)][] = $element;
            } else {
                $rows[] = [$element];
            }
        }

        foreach ($rows as $row) {
            if (count($row) === 1) {
                $html .= self::renderElement($row[0], $banner, $values);

                continue;
            }

            $cells = '';

            foreach ($row as $element) {
                $cell = self::renderElement(['width' => 100] + $element, $banner, $values);

                if ($cell !== '') {
                    $cells .= '<td style="width:'.$element['width'].'%;vertical-align:top;padding:0 4px;">'.$cell.'</td>';
                }
            }

            $html .= $cells === '' ? '' : '<table style="width:100%;border-collapse:collapse;table-layout:fixed;"><tbody><tr>'.$cells.'</tr></tbody></table>';
        }

        if ($html === '') {
            return '';
        }

        if ($zone === 'header') {
            $text = DocumentAppearance::contrast($bannerColor);

            return '<div class="layout-elements layout-elements-header" style="margin:0 0 12px 0;padding:14px 20px;background:'.$bannerColor.';color:'.$text.';">'.$html.'</div>';
        }

        $padding = in_array($zone, ['body', 'intro'], true) ? 'padding:0 20px;' : '';

        if ($background !== '') {
            $padding = 'padding:14px 20px;background:'.$background.';color:'.DocumentAppearance::contrast($background).';';
        }

        return '<div class="layout-elements layout-elements-'.$zone.'" style="margin:0 0 12px 0;'.$padding.'">'.$html.'</div>';
    }

    /**
     * @param  array<int, array<string, mixed>>  $items
     */
    private static function tableStripeColor(array $element, int $row, int $column, ?int $sourceRow = null): string
    {
        $direction = $element['stripe_direction'] ?? 'none';

        if (! in_array($direction, ['rows', 'columns'], true)) {
            return $element['cell_backgrounds'][$sourceRow ?? $row][$column] ?? $element['table_background'] ?? '';
        }

        $index = $direction === 'columns' ? $column : $row;

        return $index % 2 === 0
            ? ($element['stripe_color_a'] ?? '#ffffff')
            : ($element['stripe_color_b'] ?? '#f3f4f6');
    }

    private static function tableTextStyle(array $element, int $row, int $column, string $color, bool $header = false, bool $label = false, ?int $cellColumn = null): array
    {
        return array_replace($element, [
            'bold' => $header || $label || $element['bold'],
            'italic' => $label ? false : $element['italic'],
            'color' => ($element['column_colors'][$column] ?? null) ?: ($header ? $element['header_color'] : $color),
        ], $element['row_styles'][$row] ?? [], $element['cell_styles'][$row][$cellColumn ?? $column] ?? []);
    }

    private static function tableTextCss(array $style): string
    {
        $family = self::FONT_FAMILIES[$style['font_family'] ?? 'default'] ?? '';

        return ($family !== '' ? 'font-family:'.str_replace('"', "'", $family).';' : '')
            .'font-size:'.$style['font_size'].'px;color:'.$style['color'].';'
            .'font-weight:'.($style['bold'] ? 'bold' : 'normal').';'
            .'font-style:'.($style['italic'] ? 'italic' : 'normal').';'
            .'text-decoration:'.(! empty($style['underline']) ? 'underline' : 'none').';'
            .'line-height:'.($style['line_height'] ?? 1.35).';text-align:'.$style['align'].';';
    }

    private static function renderFreeHeader(array $items, string $bannerColor, array $values, int $headerHeight): string
    {
        $hasPdf = collect($items)->contains(fn (array $element): bool => isset($element['pdf_page']));
        if ($hasPdf) {
            $pages = [];
            foreach ($items as $element) {
                $pages[$element['pdf_page'] ?? 'layout'][] = $element;
            }
            $html = '';
            foreach ($pages as $page) {
                $height = $page[0]['pdf_page_height'] ?? $headerHeight;
                $content = '';
                foreach ($page as $element) {
                    $inner = self::renderElement(['width' => 100] + $element, false, $values);
                    $content .= '<div style="position:absolute;left:'.$element['x'].'%;top:'.$element['y'].'px;width:'.$element['width'].'%;">'.$inner.'</div>';
                }
                $html .= '<div data-pdf-page="true" style="position:relative;width:700px;height:'.$height.'px;background:#ffffff;">'.$content.'</div>';
            }

            return '<div class="layout-elements layout-elements-header">'.$html.'</div>';
        }
        $html = '';

        foreach ($items as $element) {
            $inner = self::renderElement(['width' => 100] + $element, true, $values);

            if ($inner === '') {
                continue;
            }

            $html .= sprintf(
                '<div style="position:absolute;left:%s%%;top:%dpx;width:%s%%;">%s</div>',
                rtrim(rtrim(number_format((float) ($element['x'] ?? 0), 1, '.', ''), '0'), '.') ?: '0',
                (int) ($element['y'] ?? 0),
                (string) $element['width'],
                $inner,
            );
        }

        if ($html === '') {
            return '';
        }

        $height = max(60, $headerHeight);
        $text = DocumentAppearance::contrast($bannerColor);

        return '<div class="layout-elements layout-elements-header" style="position:relative;height:'.$height.'px;margin:0 0 12px 0;background:'.$bannerColor.';color:'.$text.';">'.$html.'</div>';
    }

    /**
     * @param  array<string, mixed>  $element
     */
    private static function pdfTextLines(string $content, array $element): array
    {
        $lines = preg_split('/\r?\n/', $content);
        if (! isset($element['pdf_line_count'])) {
            return $lines;
        }
        $counts = in_array($element['list_style'] ?? 'none', ['bullet', 'numbered'], true) ? ($element['pdf_list_lines'] ?? null) : null;
        $length = max(count($lines), $counts !== null ? count($counts) : $element['pdf_line_count']);
        $output = [];
        for ($index = 0; $index < $length; $index++) {
            $line = ($lines[$index] ?? '') !== '' ? $lines[$index] : "\u{00a0}";
            $output[] = $line.($counts !== null ? str_repeat("\n\u{00a0}", max(0, ($counts[$index] ?? 1) - 1)) : '');
        }

        return $output;
    }

    private static function renderElement(array $element, bool $banner = false, array $values = []): string
    {
        $align = $element['align'];
        $margin = match ($align) {
            'center' => '0 auto',
            'right' => '0 0 0 auto',
            default => '0',
        };
        $wrapper = 'width:'.$element['width'].'%;margin:'.$margin.';text-align:'.$align.';';
        $family = self::FONT_FAMILIES[$element['font_family'] ?? 'default'] ?? '';
        if ($pdfFont = ImportedPdfFont::family($element['pdf_font_src'] ?? null)) {
            $family = $pdfFont;
        }
        $family = $family !== '' ? 'font-family:'.str_replace('"', "'", $family).';' : '';
        $color = $banner && $element['color'] === '#111827' ? 'inherit' : $element['color'];
        $lineHeight = isset($element['pdf_line_spacing']) ? $element['pdf_line_spacing'] / $element['font_size'] : ($element['line_height'] ?? 1.35);
        $textExtras = 'line-height:'.$lineHeight.';'
            .'text-decoration:'.(! empty($element['underline']) ? 'underline' : 'none').';';

        switch ($element['type']) {
            case 'image':
                if ($element['src'] === '') {
                    return '';
                }

                return '<div style="'.$wrapper.'padding:'.(! empty($element['pdf_background']) ? '0' : '4px 0').';"><img src="'.e($element['src']).'" alt="" style="display:block;width:100%;height:auto;"></div>';

            case 'divider':
                return '<div style="'.$wrapper.'height:0;margin-top:6px;margin-bottom:6px;border-top:'.$element['height'].'px solid '.$color.';"></div>';

            case 'spacer':
                return '<div style="height:'.$element['height'].'px;"></div>';

            case 'table':
                $columnCount = $element['cells'] !== null ? count($element['cells'][0] ?? []) : min(3, $element['columns']) * 2;
                $widths = $element['column_widths'];
                if (count($widths) === $columnCount && array_sum($widths) > 0) {
                    $total = array_sum($widths);
                    $widths = array_map(fn ($width) => $width / $total * 100, $widths);
                } else {
                    $widths = array_map(fn ($index) => $element['cells'] !== null ? 100 / max(1, $columnCount)
                        : ($index % 2 === 0 ? $element['label_width'] : 100 - $element['label_width']) / ($columnCount / 2),
                        range(0, max(0, $columnCount - 1)));
                }
                if ($element['cells'] !== null) {
                    $tableBackground = $element['row_heights'] !== [] ? 'background-color:'.($element['table_background'] ?: 'transparent').';' : '';
                    $html = '<table style="'.$wrapper.$tableBackground.'border-collapse:collapse;table-layout:fixed;"><tbody>';
                    $border = $element['border'] ? '1px solid '.$element['border_color'] : 'none';
                    foreach ($element['cells'] as $rowIndex => $row) {
                        $html .= '<tr>';
                        $header = $rowIndex === 0 && $element['header_row'];
                        $tag = $header ? 'th' : 'td';
                        foreach ($row as $columnIndex => $cell) {
                            $span = $element['cell_spans'][$rowIndex][$columnIndex] ?? ['rows' => 1, 'columns' => 1];
                            if ($span['rows'] === 0 || $span['columns'] === 0) {
                                continue;
                            }
                            $background = $header
                                ? ($element['label_bg'] ?: '#065f46')
                                : self::tableStripeColor($element, $rowIndex - ($element['header_row'] ? 1 : 0), $columnIndex, $rowIndex);
                            $style = $background !== '' ? 'background-color:'.$background.';' : '';
                            $textStyle = self::tableTextStyle($element, $rowIndex, $columnIndex, $color, $header);
                            $height = isset($element['row_heights'][$rowIndex]) ? 'height:'.array_sum(array_slice($element['row_heights'], $rowIndex, $span['rows'])).'px;' : '';
                            $padding = $element['row_heights'] !== [] ? '2px 6px' : '6px 10px';
                            $cellBorders = '';
                            if ($element['border']) {
                                foreach ($element['cell_borders'][$rowIndex][$columnIndex] ?? [] as $side => $value) {
                                    $cellBorders .= 'border-'.$side.':'.$value.';';
                                }
                            }
                            $cellWidth = array_sum(array_slice($widths, $columnIndex, $span['columns']));
                            $html .= '<'.$tag.' colspan="'.$span['columns'].'" rowspan="'.$span['rows'].'" style="width:'.$cellWidth.'%;'.$height.$style.self::tableTextCss($textStyle).'white-space:pre-line;overflow-wrap:anywhere;padding:'.$padding.';border:'.$border.';'.$cellBorders.'">'
                                .e(DocumentTextCase::transform(self::replaceFields($cell, $values), $textStyle['text_case'])).'</'.$tag.'>';
                        }
                        $html .= '</tr>';
                    }

                    return $html.'</tbody></table>';
                }
                $rows = [];

                foreach ($element['items'] as $index => $item) {
                    $value = trim(self::replaceFields($item['value'], $values));
                    $label = trim(self::replaceFields($item['label'], $values));

                    if (($value === '' && str_contains($item['value'], '{{')) || ($value === '' && $label === '')) {
                        continue;
                    }

                    $rows[] = [$label, $value, $index];
                }

                if ($rows === []) {
                    return '';
                }

                $pairs = $element['columns'] > 3 ? 3 : $element['columns'];
                $line = $element['border'] ? 'border:1px solid '.$element['border_color'].';' : '';
                $labelBg = $element['label_bg'] !== '' ? 'background:'.$element['label_bg'].';' : '';
                $base = 'padding:6px 10px;vertical-align:middle;'.$line;
                $html = '<table style="'.$wrapper.'border-collapse:collapse;table-layout:fixed;"><tbody>';

                foreach (array_chunk($rows, $pairs) as $rowIndex => $chunk) {
                    $html .= '<tr>';
                    for ($i = 0; $i < $pairs; $i++) {
                        $labelWidth = $widths[$i * 2];
                        $valueWidth = $widths[$i * 2 + 1];
                        $row = $chunk[$i] ?? ['', '', -1];
                        $labelStripe = self::tableStripeColor($element, $rowIndex, $i * 2);
                        $valueStripe = self::tableStripeColor($element, $rowIndex, $i * 2 + 1);
                        $labelBackground = $labelStripe !== '' ? 'background-color:'.$labelStripe.';' : $labelBg;
                        $valueBackground = $valueStripe !== '' ? 'background-color:'.$valueStripe.';' : '';
                        $labelStyle = self::tableTextStyle($element, $row[2], $i * 2, $color, false, true, 0);
                        $valueStyle = self::tableTextStyle($element, $row[2], $i * 2 + 1, $color, false, false, 1);
                        $html .= '<td style="width:'.$labelWidth.'%;'.$labelBackground.$base.self::tableTextCss($labelStyle).'">'.e(DocumentTextCase::transform($row[0], $labelStyle['text_case'])).'</td>';
                        $html .= '<td style="width:'.$valueWidth.'%;'.$valueBackground.$base.self::tableTextCss($valueStyle).'">'.e(DocumentTextCase::transform($row[1], $valueStyle['text_case'])).'</td>';
                    }
                    $html .= '</tr>';
                }

                return $html.'</tbody></table>';

            case 'company':
                $rows = [];

                foreach ($element['fields'] as $key) {
                    $value = trim($values[$key] ?? '');

                    if ($value !== '') {
                        $rows[] = [self::COMPANY_FIELDS[$key] ?? '', $value];
                    }
                }

                if ($rows === []) {
                    return '';
                }

                $cell = fn (array $row): string => $element['show_labels']
                    ? '<span style="opacity:.65;">'.e(DocumentTextCase::transform($row[0], $element['text_case'])).':</span> '.e(DocumentTextCase::transform($row[1], $element['text_case']))
                    : e(DocumentTextCase::transform($row[1], $element['text_case']));
                $textStyle = sprintf(
                    '%sfont-size:%dpx;color:%s;font-weight:%s;font-style:%s;%s',
                    $family,
                    $element['font_size'],
                    $color,
                    $element['bold'] ? 'bold' : 'normal',
                    $element['italic'] ? 'italic' : 'normal',
                    $textExtras,
                );

                if ($element['layout'] === 'table') {
                    $border = $element['border'] ? 'border:1px solid '.$color.';' : '';
                    $html = '<table style="'.$wrapper.'border-collapse:collapse;table-layout:fixed;"><tbody>';

                    foreach (array_chunk($rows, $element['columns']) as $chunk) {
                        $html .= '<tr>';
                        foreach ($chunk as $row) {
                            $html .= '<td style="'.$textStyle.$border.'padding:4px 8px;vertical-align:top;">'.$cell($row).'</td>';
                        }
                        for ($i = count($chunk); $i < $element['columns']; $i++) {
                            $html .= '<td style="'.$border.'padding:4px 8px;"></td>';
                        }
                        $html .= '</tr>';
                    }

                    return $html.'</tbody></table>';
                }

                $html = '';
                foreach ($rows as $row) {
                    $html .= '<div style="'.$wrapper.$textStyle.'padding:1px 0;">'.$cell($row).'</div>';
                }

                return $html;

            case 'date':
                $content = now()->format('F j, Y');
                break;
            case 'validity':
                $key = 'validity_'.($element['validity_days'] ?? 30);
                $content = $values[$key] ?? now()->addDays($element['validity_days'] ?? 30)->format('F j, Y');
                break;

            default:
                $content = self::replaceFields((string) $element['content'], $values);
        }

        if (trim($content) === '' && ! isset($element['pdf_line_count'])) {
            return '';
        }

        $style = sprintf(
            '%s%sfont-size:%spx;color:%s;font-weight:%s;font-style:%s;padding:%s;%s',
            $wrapper,
            $family,
            $element['font_size'],
            $color,
            $element['bold'] ? 'bold' : 'normal',
            $element['italic'] ? 'italic' : 'normal',
            isset($element['pdf_page']) ? '0' : '2px 0',
            $textExtras,
        );
        if (isset($element['pdf_page'])) {
            $style .= 'white-space:pre;';
        }

        if ($element['type'] === 'text' && in_array($element['list_style'] ?? 'none', ['bullet', 'numbered'], true)) {
            $tag = $element['list_style'] === 'numbered' ? 'ol' : 'ul';
            $list = $tag === 'ol' ? 'decimal' : ($element['pdf_bullet_style'] ?? 'disc');
            $lines = self::pdfTextLines($content, $element);
            $padding = isset($element['pdf_page']) ? '0' : '2px 0';
            $items = array_map(fn (string $line): string => '<li style="padding:'.$padding.';">'
                .str_replace(["\r\n", "\n"], '<br>', e(DocumentTextCase::transform($line, $element['text_case']))).'</li>', $lines);

            return '<div style="'.$style.'padding:0;"><'.$tag.' style="margin:0;padding-left:20px;list-style-type:'.$list.';">'.implode('', $items).'</'.$tag.'></div>';
        }

        if (! empty($element['pdf_text_runs'])) {
            $lines = self::pdfTextLines($content, $element);
            $runs = $element['pdf_text_runs'];
            $html = '';
            $caseStates = [];
            foreach ($runs as $index => $run) {
                $last = ! array_filter(array_slice($runs, $index + 1), fn (array $next): bool => $next['line'] === $run['line']);
                $text = mb_substr($lines[$run['line']] ?? '', $run['offset'], $last ? null : $run['length']);
                $font = ImportedPdfFont::family($run['pdf_font_src'] ?? null);
                $runFamily = ($font ? '"'.$font.'", ' : '').self::FONT_FAMILIES[$run['font_family']];
                $attribute = $font ? ' data-pdf-font-src="'.e($run['pdf_font_src']).'"' : '';
                $y = isset($element['pdf_line_spacing']) ? $run['y'] : $run['line'] * $element['font_size'] * ($element['line_height'] ?? 1.35);
                $caseStates[$run['line']] ??= ['capitalizeNext' => false, 'hasWord' => false];
                $html .= '<span'.$attribute.' style="position:absolute;left:'.$run['x'].'px;top:'.$y.'px;width:'.$run['width'].'px;min-height:'.$run['height'].'px;font-family:'.e($runFamily).';font-size:'.$run['font_size'].'px;font-weight:'.($run['bold'] ? 'bold' : 'normal').';font-style:'.($run['italic'] ? 'italic' : 'normal').';color:'.$run['color'].';line-height:1;white-space:pre;font-synthesis:none;">'
                    .e(DocumentTextCase::transform($text, $element['text_case'], $caseStates[$run['line']])).'</span>';
            }

            return '<div style="'.$style.'position:relative;height:'.$element['height'].'px;">'.$html.'</div>';
        }

        $content = DocumentTextCase::transform(implode("\n", self::pdfTextLines($content, $element)), $element['text_case']);

        $fontAttribute = ImportedPdfFont::family($element['pdf_font_src'] ?? null)
            ? ' data-pdf-font-src="'.e($element['pdf_font_src']).'"' : '';

        $html = isset($element['pdf_line_count']) ? str_replace(["\r\n", "\n"], '<br>', e($content)) : nl2br(e($content));

        return '<div'.$fontAttribute.' style="'.$style.'">'.$html.'</div>';
    }

    /**
     * Replaces the generated hero with the header zone (or inserts it after <body>) and the footer zone before </body>.
     *
     * @param  list<array<string, mixed>>  $elements
     */
    public static function inject(string $html, array $elements, string $bannerColor = '#065f46', array $values = [], array $zoneColors = []): string
    {
        $elements = array_values(array_filter(
            $elements,
            fn (array $element): bool => in_array($element['zone'] ?? 'header', self::ACTIVE_ZONES, true),
        ));

        if ($elements === []) {
            return $html;
        }

        $header = self::render($elements, 'header', $bannerColor, $values, headerHeight: (int) ($zoneColors['header_height'] ?? self::DEFAULT_HEADER_HEIGHT));
        $footer = self::render($elements, 'footer', values: $values, background: $zoneColors['footer'] ?? '');
        $body = self::render($elements, 'body', values: $values, background: $zoneColors['body'] ?? '');
        $intro = self::render($elements, 'intro', values: $values);

        if ($body !== '') {
            $replacement = $header.$intro.$body.$footer;
            $count = 0;
            $html = preg_replace_callback(
                '/(<body\b[^>]*>).*(<\/body>)/is',
                fn (array $match): string => $match[1].$replacement.$match[2],
                $html,
                1,
                $count,
            ) ?? $html;

            return $count > 0 ? $html : $html.$replacement;
        }

        $introPlaced = false;

        if ($intro !== '') {
            $end = self::heroEnd($html);

            if ($end !== null) {
                $html = substr_replace($html, $intro, $end, 0);
                $introPlaced = true;
            }
        }

        if ($header !== '') {
            $hide = '<style>.hero{display:none!important}</style>';
            $count = 0;
            $html = preg_replace_callback(
                '/<div\s+class="hero"/i',
                fn (array $match): string => $hide.$header.$match[0],
                $html,
                1,
                $count,
            ) ?? $html;

            if ($count === 0) {
                $html = preg_replace_callback(
                    '/<body\b[^>]*>/i',
                    fn (array $match): string => $match[0].$header.($introPlaced ? '' : $intro),
                    $html,
                    1,
                ) ?? $html;
            }
        }

        if ($header === '') {
            $html = preg_replace('/<\/head>/i', '<style>.hero{display:none!important}</style></head>', $html, 1, $hidden) ?? $html;

            if ($hidden === 0) {
                $html = '<style>.hero{display:none!important}</style>'.$html;
            }
        }

        if ($header === '' && $intro !== '' && ! $introPlaced) {
            $html = preg_replace_callback(
                '/<body\b[^>]*>/i',
                fn (array $match): string => $match[0].$intro,
                $html,
                1,
            ) ?? $html;
        }

        if ($footer !== '') {
            $position = strripos($html, '</body>');
            $html = $position === false
                ? $html.$footer
                : substr_replace($html, $footer, $position, 0);
        }

        return $html;
    }

    private static function heroEnd(string $html): ?int
    {
        if (preg_match('/<div\s+class="hero"[^>]*>/i', $html, $start, PREG_OFFSET_CAPTURE) !== 1) {
            return null;
        }

        $depth = 1;
        $offset = $start[0][1] + strlen($start[0][0]);

        while ($depth > 0 && preg_match('/<(\/?)div\b[^>]*>/i', $html, $tag, PREG_OFFSET_CAPTURE, $offset) === 1) {
            $depth += $tag[1][0] === '/' ? -1 : 1;
            $offset = $tag[0][1] + strlen($tag[0][0]);
        }

        return $depth === 0 ? $offset : null;
    }
}
