<?php

namespace App\Support;

class DocumentLayoutElements
{
    public const TYPES = ['text', 'image', 'divider', 'spacer', 'date'];

    public const ZONES = ['header', 'body', 'footer'];

    public const ALIGNMENTS = ['left', 'center', 'right'];

    public const MAX_ELEMENTS = 150;

    public const FIELDS = [
        'company_name' => ['label' => 'Company name', 'group' => 'Company', 'sample' => 'Gateway Door Systems'],
        'company_address' => ['label' => 'Company address', 'group' => 'Company', 'sample' => '245 Market Street · Portland, OR 97201'],
        'company_phone' => ['label' => 'Company phone', 'group' => 'Company', 'sample' => '(503) 555-0142'],
        'company_email' => ['label' => 'Company email', 'group' => 'Company', 'sample' => 'info@example.com'],
        'document_title' => ['label' => 'Document title', 'group' => 'Document', 'sample' => 'Northwest Commons'],
        'document_number' => ['label' => 'Document number', 'group' => 'Document', 'sample' => 'BID-2025-014'],
        'generated_date' => ['label' => 'Date generated', 'group' => 'Document', 'sample' => 'October 7, 2025'],
        'generated_by' => ['label' => 'Generated by', 'group' => 'Document', 'sample' => 'Alex Morgan'],
        'year' => ['label' => 'Year', 'group' => 'Document', 'sample' => '2025'],
        'project_name' => ['label' => 'Project name', 'group' => 'Project', 'sample' => 'Northwest Commons'],
        'project_number' => ['label' => 'Project number', 'group' => 'Project', 'sample' => 'P-2025-014'],
        'project_address' => ['label' => 'Project address', 'group' => 'Project', 'sample' => '245 Market Street, Portland, OR'],
    ];

    /**
     * Field catalog for the editor, using real company values when available.
     *
     * @return list<array<string, string>>
     */
    public static function fieldCatalog(): array
    {
        $company = self::companyValues();
        $catalog = [];

        foreach (self::FIELDS as $key => $meta) {
            $catalog[] = [
                'key' => $key,
                'label' => $meta['label'],
                'group' => $meta['group'],
                'sample' => ($company[$key] ?? '') !== '' ? $company[$key] : $meta['sample'],
            ];
        }

        return $catalog;
    }

    /**
     * @return array<string, string>
     */
    public static function companyValues(): array
    {
        $company = DocumentLogo::company();

        if (! $company) {
            return [];
        }

        $address = implode(' · ', array_filter([
            $company->address_line_1,
            $company->address_line_2,
            implode(', ', array_filter([$company->city, $company->state, $company->postal_code])),
            $company->country,
        ]));

        return [
            'company_name' => (string) $company->name,
            'company_address' => $address,
            'company_phone' => (string) ($company->contact_phone_number ?: $company->phone_number),
            'company_email' => (string) $company->email,
        ];
    }

    /**
     * Resolves every merge field for a document using its view data.
     *
     * @param  array<string, mixed>  $data
     * @return array<string, string>
     */
    public static function fieldValues(array $data): array
    {
        $company = self::companyValues();
        $pick = fn (string $key, string $fallback = ''): string => (string) ($data[$key] ?? $fallback);

        return [
            'company_name' => $company['company_name'] ?? $pick('companyName'),
            'company_address' => $company['company_address'] ?? $pick('companyAddress'),
            'company_phone' => $company['company_phone'] ?? $pick('companyPhone'),
            'company_email' => $company['company_email'] ?? $pick('companyEmail'),
            'document_title' => $pick('title'),
            'document_number' => $pick('bidNumber', $pick('quotationNumber', $pick('projectNumber'))),
            'generated_date' => now()->format('F j, Y'),
            'generated_by' => $pick('generatedBy'),
            'year' => (string) now()->year,
            'project_name' => $pick('projectName'),
            'project_number' => $pick('projectNumber'),
            'project_address' => $pick('projectAddress'),
        ];
    }

    /**
     * @param  array<string, string>  $values
     */
    public static function replaceFields(string $text, array $values): string
    {
        return preg_replace_callback(
            '/\{\{\s*([a-z_]+)\s*\}\}/',
            fn (array $match): string => $values[$match[1]] ?? '',
            $text,
        ) ?? $text;
    }

    /**
     * @return array{body: string, footer: string}
     */
    public static function zoneColors(mixed $colors): array
    {
        $colors = is_array($colors) ? $colors : [];
        $clean = fn (mixed $value): string => is_string($value) && preg_match('/^#[A-Fa-f0-9]{6}$/', $value) === 1 ? strtolower($value) : '';

        return ['body' => $clean($colors['body'] ?? null), 'footer' => $clean($colors['footer'] ?? null)];
    }

    /**
     * Normalizes stored or submitted elements into a safe, fully-populated shape.
     *
     * @return list<array<string, mixed>>
     */
    public static function sanitize(mixed $elements): array
    {
        if (! is_array($elements)) {
            return [];
        }

        $clean = [];

        foreach (array_slice(array_values($elements), 0, self::MAX_ELEMENTS) as $index => $element) {
            if (! is_array($element) || ! in_array($element['type'] ?? null, self::TYPES, true)) {
                continue;
            }

            $id = preg_replace('/[^A-Za-z0-9_-]/', '', (string) ($element['id'] ?? ''));
            $src = (string) ($element['src'] ?? '');

            $clean[] = [
                'id' => $id !== '' ? substr($id, 0, 40) : 'el-'.$index,
                'type' => $element['type'],
                'zone' => in_array($element['zone'] ?? null, ['body', 'footer'], true) ? $element['zone'] : 'header',
                'content' => mb_substr((string) ($element['content'] ?? ''), 0, 1000),
                'src' => EditorImage::isStoredSrc($src) ? $src : '',
                'align' => in_array($element['align'] ?? null, self::ALIGNMENTS, true) ? $element['align'] : 'left',
                'width' => max(5, min(100, (int) ($element['width'] ?? 100))),
                'height' => max(1, min(400, (int) ($element['height'] ?? 16))),
                'font_size' => max(8, min(48, (int) ($element['font_size'] ?? 12))),
                'text_case' => DocumentTextCase::normalize((string) ($element['text_case'] ?? 'original')),
                'bold' => (bool) ($element['bold'] ?? false),
                'italic' => (bool) ($element['italic'] ?? false),
                'color' => DocumentAppearance::normalize((string) ($element['color'] ?? ''), '#111827'),
            ];
        }

        return $clean;
    }

    /**
     * @param  list<array<string, mixed>>  $elements
     */
    public static function render(array $elements, string $zone, string $bannerColor = '#065f46', array $values = [], string $background = ''): string
    {
        $items = array_filter(
            $elements,
            fn (array $element): bool => ($element['zone'] ?? 'header') === $zone,
        );

        if ($items === []) {
            return '';
        }

        $html = '';

        foreach ($items as $element) {
            $html .= self::renderElement($element, $zone === 'header' || $background !== '', $values);
        }

        if ($zone === 'header') {
            $text = DocumentAppearance::contrast($bannerColor);

            return '<div class="layout-elements layout-elements-header" style="margin:0 0 12px 0;padding:14px 20px;background:'.$bannerColor.';color:'.$text.';">'.$html.'</div>';
        }

        $padding = $zone === 'body' ? 'padding:0 20px;' : '';

        if ($background !== '') {
            $padding = 'padding:14px 20px;background:'.$background.';color:'.DocumentAppearance::contrast($background).';';
        }

        return '<div class="layout-elements layout-elements-'.$zone.'" style="margin:0 0 12px 0;'.$padding.'">'.$html.'</div>';
    }

    /**
     * @param  array<string, mixed>  $element
     */
    private static function renderElement(array $element, bool $banner = false, array $values = []): string
    {
        $align = $element['align'];
        $margin = match ($align) {
            'center' => '0 auto',
            'right' => '0 0 0 auto',
            default => '0',
        };
        $wrapper = sprintf('width:%d%%;margin:%s;text-align:%s;', $element['width'], $margin, $align);
        $color = $banner && $element['color'] === '#111827' ? 'inherit' : $element['color'];

        switch ($element['type']) {
            case 'image':
                if ($element['src'] === '') {
                    return '';
                }

                return '<div style="'.$wrapper.'padding:4px 0;"><img src="'.e($element['src']).'" alt="" style="width:100%;height:auto;"></div>';

            case 'divider':
                return '<div style="'.$wrapper.'height:0;margin-top:6px;margin-bottom:6px;border-top:'.$element['height'].'px solid '.$color.';"></div>';

            case 'spacer':
                return '<div style="height:'.$element['height'].'px;"></div>';

            case 'date':
                $content = now()->format('F j, Y');
                break;

            default:
                $content = self::replaceFields((string) $element['content'], $values);
        }

        if (trim($content) === '') {
            return '';
        }

        $style = sprintf(
            '%sfont-size:%dpx;color:%s;font-weight:%s;font-style:%s;padding:2px 0;line-height:1.35;',
            $wrapper,
            $element['font_size'],
            $color,
            $element['bold'] ? 'bold' : 'normal',
            $element['italic'] ? 'italic' : 'normal',
        );

        $content = DocumentTextCase::transform($content, $element['text_case']);

        return '<div style="'.$style.'">'.nl2br(e($content)).'</div>';
    }

    /**
     * Replaces the generated hero with the header zone (or inserts it after <body>) and the footer zone before </body>.
     *
     * @param  list<array<string, mixed>>  $elements
     */
    public static function inject(string $html, array $elements, string $bannerColor = '#065f46', array $values = [], array $zoneColors = []): string
    {
        if ($elements === []) {
            return $html;
        }

        $header = self::render($elements, 'header', $bannerColor, $values);
        $footer = self::render($elements, 'footer', values: $values, background: $zoneColors['footer'] ?? '');
        $body = self::render($elements, 'body', values: $values, background: $zoneColors['body'] ?? '');

        if ($body !== '') {
            $replacement = $header.$body.$footer;
            $count = 0;
            $html = preg_replace_callback(
                '/(<body\b[^>]*>).*(<\/body>)/is',
                fn (array $match): string => $match[1].$replacement.$match[2],
                $html,
                1,
                $count,
            ) ?? $html;

            return $count > 0 ? $html : $html.$replacement;
        }

        if ($header !== '') {
            $hide = '<style>.hero{display:none!important}</style>';
            $count = 0;
            $html = preg_replace_callback(
                '/<div\s+class="hero"/i',
                fn (array $match): string => $hide.$header.$match[0],
                $html,
                1,
                $count,
            ) ?? $html;

            if ($count === 0) {
                $html = preg_replace_callback(
                    '/<body\b[^>]*>/i',
                    fn (array $match): string => $match[0].$header,
                    $html,
                    1,
                ) ?? $html;
            }
        }

        if ($footer !== '') {
            $position = strripos($html, '</body>');
            $html = $position === false
                ? $html.$footer
                : substr_replace($html, $footer, $position, 0);
        }

        return $html;
    }
}
